@startuml classes

    namespace Anser.EntityAdministration #DDDDDD {

        class Province {
            string name : "nom"
            int population : "population"
            float area : "surface"
            float income : "Revenu total"
            geometry geom : "Données Geometrique"
        }

        class Territory {
            string name : "nom"
            int population : "population"
            float area : "surface"
            float income : "Revenu total"
            geometry geom : "Données Geometrique"
        }

        class City {
            string name : "nom"
            int population : "population"
            float area : "surface"
            float income : "Revenu total"
            geometry geom : "Données Geometrique"
        }
        
        class Sector {
            string name : "nom"
            int population : "population"
            float area : "surface"
            float income : "Revenu total"
            geometry geom : "Données Geometrique"
        }

        class Locality {
            string name : "nom"
            int population : "population"
            float area : "surface"
            float income : "Revenu total"
            geometry geom : "Données Geometrique"
        }
        circle circle1

    }

    namespace Anser.ExistingPlants #C2D2DE {

        class ExistingPlant {
            string name : "nom"
            geaometry geom : "Données Geometrique"
            float power : "Puissance installée/ disponible [KW]"
            int nbrOfhouseholds : "Nombre de ménages connectés"
            float powerForProductiveUsed : "Puissance ménages [KW]"
            float powerForProductiveUsed : "Puissance usage productif/ industriel"
        }

        class ExistingPlantType {
            string name : "nom"
        }

        class OwnerAndOrOSER {
            string name : "nom"
            bool isOwner() : "message verification si l'instant est Propriétaire"
            bool isOSER() : "message verification si l'instant est OSER"

        }
        circle circle2
    }

    namespace Anser.ExistingPowerLines #A2A2DE {

        class PowerLine {

            float tension : "Tension de la ligne"
            float tension : "Tension de la ligne"
            geometry geom : "Données Geometrique"
        }

        class PowerLineType {
            string wording : "denomination du type de la ligne"
        }

        class Nature {
            string wording : "denomination de la Nature de la ligne"
        }
        circle circle3
    }

    namespace Anser.IndividualSets #92A2AE {

        class IndividualSet {
            string wording : "Denomination du Kit individuel"
            string nbrhouseholdsConnected : "Nombre des ménages connectés"
            float powerAvailable : "Puissance disponible [KW]"
            geometry geom : "Données géographique"
        }
        circle circle4
    }

@enduml
