@startuml relationShip

    Anser.EntityAdministration.Province "1" <-left- "many" Anser.EntityAdministration.City
    Anser.EntityAdministration.Province "1" <-right- "many" Anser.EntityAdministration.Territory

    Anser.ExistingPlants.ExistingPlant "many" -up-> "many" Anser.EntityAdministration.Town
    Anser.ExistingPlants.ExistingPlant "many" -up-> "many" Anser.EntityAdministration.Locality
    Anser.ExistingPlants.ExistingPlant "many" -right-> "1" Anser.ExistingPlants.ExistingPlantType
    Anser.ExistingPlants.ExistingPlant "many" -left-> "1" Anser.ExistingPlants.OwnerAndOrOSER


    Anser.ExistingPowerLines.PowerLine "many" -left-> "many" Anser.ExistingPowerLines.PowerLineType
    Anser.ExistingPowerLines.PowerLine "many" -right-> "many" Anser.ExistingPowerLines.Nature


    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Territory
    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Sector
    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Locality


    Anser.Hydroelectricotential.Hydroelectricotential "many" -up-> "many" Anser.EntityAdministration.Locality

    Anser.Health.HealthZone "1" <-up- "many" Anser.Health.HealthInstitution
    Anser.Health.HealthInstitutionCategory "1" <-up- "many" Anser.Health.HealthInstitution
    Anser.Health.HealthInstitutionService "1" <-up- "many" Anser.Health.HealthInstitution

    Anser.Telecommunication.TelecommunicationOperator "1" <-up- "many" Anser.Telecommunication.TelecommunicationNetworkAccessPoint
    Anser.Telecommunication.TelecommunicationOperator "1" <-down- "many" Anser.Telecommunication.MobileSubscriberBase

    Anser.WaysOfCommunication.WayOfCommunicationType "1" <-left- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.ModeOfTransport "1" <-right- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.RoadSurface "1" <-up- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.RoadSurface "1" <-down- "many" Anser.WaysOfCommunication.AccessibleSection
    Anser.WaysOfCommunication.WayOfCommunication "1" <-down- "many" Anser.WaysOfCommunication.AccessibleSection
    Anser.WaysOfCommunication.WayOfCommunication "1" <-up- "many" Anser.EntityAdministration.Locality


    Anser.LocalEconomy.EconomicActivityType "1" <-up- "many" Anser.LocalEconomy.EconomicActivity
    Anser.LocalEconomy.Equipment "many" <-up- "many" Anser.LocalEconomy.EconomicActivity
    Anser.LocalEconomy.ConsumptionCenter "many" <-down- "many" Anser.LocalEconomy.EconomicActivity

    Anser.Projects.ProjectType "1" <-up- "many" Anser.Projects.Project
    Anser.Projects.ProjectState "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.ProgressStatus "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.Project "1" <-up- "many" Anser.Projects.Line
    Anser.Projects.Project "1" <-down- "many" Anser.Projects.Transformers
    Anser.Projects.Project "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.Project "1" <-left- "many" Anser.ExistingPlants.OwnerAndOrOSER
    Anser.Projects.Project "many" <-right- "many" Anser.EntityAdministration.Locality



@enduml