@startuml relationShip

    Anser.EntityAdministration.Province "1" <-left- "many" Anser.EntityAdministration.City
    Anser.EntityAdministration.Province "1" <-right- "many" Anser.EntityAdministration.Territory

    Anser.ExistingPlants.ExistingPlant "many" -up-> "many" Anser.EntityAdministration.Town
    Anser.ExistingPlants.ExistingPlant "many" -up-> "many" Anser.EntityAdministration.Locality
    Anser.ExistingPlants.ExistingPlant "many" -right-> "1" Anser.ExistingPlants.ExistingPlantType
    Anser.ExistingPlants.ExistingPlant "many" -left-> "1" Anser.ExistingPlants.OwnerAndOrOSER



    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Territory
    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Sector
    Anser.IndividualSets.IndividualSet "many" -down-> "many" Anser.EntityAdministration.Locality


    Anser.Hydroelectricotential.Hydroelectricotential "many" -down-> "many" Anser.EntityAdministration.Locality


    Anser.WaysOfCommunication.WayOfCommunicationType "1" <-left- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.ModeOfTransport "1" <-right- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.RoadSurface "1" <-up- "many" Anser.WaysOfCommunication.WayOfCommunication
    Anser.WaysOfCommunication.RoadSurface "1" <-down- "many" Anser.WaysOfCommunication.AccessibleSection
    Anser.WaysOfCommunication.WayOfCommunication "1" <-down- "many" Anser.WaysOfCommunication.AccessibleSection
    Anser.WaysOfCommunication.WayOfCommunication "1" <-up- "many" Anser.EntityAdministration.Locality


    Anser.Projects.ProjectType "1" <-up- "many" Anser.Projects.Project
    Anser.Projects.ProjectState "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.ProgressStatus "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.Project "1" <-up- "many" Anser.Projects.Line
    Anser.Projects.Project "1" <-down- "many" Anser.Projects.Transformers
    Anser.Projects.Project "1" <-down- "many" Anser.Projects.Project
    Anser.Projects.Project "1" <-left- "many" Anser.ExistingPlants.OwnerAndOrOSER
    Anser.Projects.Project "many" <-right- "many" Anser.EntityAdministration.Locality



@enduml